ateupeonding:
  api-prefix: api/v1/**

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: core_service
          uri: ${CORE_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/core-service/${ateupeonding.api-prefix}
        - id: content_service
          uri: ${CONTENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/content-service/${ateupeonding.api-prefix}
        - id: payment_service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/payment-service/${ateupeonding.api-prefix}
        - id: user_service
          uri: ${USER_SERVICE_URL:http://localhost:9004}
          predicates:
            - Path=/user-service/${ateupeonding.api-prefix}